### ISSUE TITLE
部署过程出现错误

### ISSUE THREAD

**Issue by qhmorz** [racpast/Pixiv-Nginx-GUI#1]
![$Q5WP~M0X7 5G%_WPX94@KN](https://github.com/user-attachments/assets/676b7c99-1ce8-40d6-be3b-08135047bb98)

**Comment by racpast** [comment]
您好，很抱歉由于窗体设计欠佳导致您对按钮的功能有所误解！
**在正常情况下， “重试”和“从本地文件安装”按钮是无需使用的。**
如下图，**当窗体中显示“文件下载完成”以及“文件解压完成”后，您就可以直接点击“下一步”按钮继续操作了。**
![image](https://github.com/user-attachments/assets/ca47badd-d90c-4d2e-8bf2-bc297bc76399)
- “重试”按钮是在**下载失败或遇到任何错误时**使用的。
- “从本地文件安装”按钮是**多次尝试后实在无法下载成功**之后使用的。

如果您确实需要使用“从本地文件安装”，请参考以下步骤：

1. 打开[Pixiv-Nginx](https://github.com/mashirozx/Pixiv-Nginx)

**Comment by racpast** [comment]
您好，很抱歉由于窗体设计欠佳导致您对按钮的功能有所误解！
**在正常情况下， “重试”和“从本地文件安装”按钮是无需使用的。**
如下图，**当窗体中显示“文件下载完成”以及“文件解压完成”后，您就可以直接点击“下一步”按钮继续操作了。**
![image](https://github.com/user-attachments/assets/ca47badd-d90c-4d2e-8bf2-bc297bc76399)
- “重试”按钮是在**下载失败或遇到任何错误时**使用的。
- “从本地文件安装”按钮是**多次尝试后实在无法下载成功**之后使用的。

## 如果您确实需要使用“从本地文件安装”，请参考以下步骤：

1. 打开[Pixiv-Nginx](https://github.com/mashirozx/Pixiv-Nginx)仓库
2. 点击“Code>Download Zip”**下载源码压缩包**
![image](https://github.com/user-attachments/assets/f6d5590e-6667-4143-99dc-aaa37a350fdd)
3. 点击“从本地文件安装”按钮，并**选择所下载的源码压缩包**
4. 在弹出的“输入”窗口中，**输入窗口上显示的“最新版本Commit日期”，并点击确定**，如图
![image](https://github.com/user-attachments/assets/1159e0a8-3cdf-4a96-a88c-972bf846fbda)
_（请使用英文分号）_
5. 在文件解压完成后，即可**直接点击“下一步”按钮继续操作**
![image](https://github.com/user-attachments/assets/535edd26-9d50-4a14-b8c6-1115764292e2)
_非常感谢您的反馈，我们将在后续的升级中对窗体的设计及按钮的操作机制进行更为细致的优化与提升。_

**Comment by racpast** [comment]
您好，很抱歉由于窗体设计欠佳导致您对按钮的功能有所误解！
**在正常情况下， “重试”和“从本地文件安装”按钮是无需使用的。**
如下图，**当窗体中显示“文件下载完成”以及“文件解压完成”后，您就可以直接点击“下一步”按钮继续操作了。**
![image](https://github.com/user-attachments/assets/ca47badd-d90c-4d2e-8bf2-bc297bc76399)
- “重试”按钮是在**下载失败或遇到任何错误时**使用的。
- “从本地文件安装”按钮是**多次尝试后实在无法下载成功**之后使用的。

## 如果您确实需要使用“从本地文件安装”，请参考以下步骤：

1. 打开[Pixiv-Nginx](https://github.com/mashirozx/Pixiv-Nginx)仓库
2. 点击“Code>Download Zip”**下载源码压缩包**
![image](https://github.com/user-attachments/assets/f6d5590e-6667-4143-99dc-aaa37a350fdd)
3. 点击“从本地文件安装”按钮，并**选择所下载的源码压缩包**
4. 在弹出的“输入”窗口中，**输入窗口上显示的“最新版本Commit日期”，并点击确定**，如图
![image](https://github.com/user-attachments/assets/1159e0a8-3cdf-4a96-a88c-972bf846fbda)
_（请使用英文分号）_
5. 在文件解压完成后，即可**直接点击“下一步”按钮继续操作**
![image](https://github.com/user-attachments/assets/535edd26-9d50-4a14-b8c6-1115764292e2)
_非常感谢您的反馈，我们将在后续的升级中对窗体的设计及按钮的操作机制进行更为细致的优化与提升。_

**Comment by racpast** [comment]
## 您好，很抱歉之前误解了您的意思！
**我们已经成功复现该错误，并已经在最新版中更正该错误，十分感谢您的反馈！**

## 复现过程

**1. 如图，设置系统的短日期格式为yyyy/mm/d/ddd**
![image](https://github.com/user-attachments/assets/80368051-4e02-429a-80ad-046a2b1413fb)
**2. 运行程序并开始部署，下载解压完成后自动弹出`该字符串未被识别为有效的 DateTime。`错误。**
![9fd6470329a9418683641f5f08c511b4](https://github.com/user-attachments/assets/8bd8b2f1-541f-4a6e-8f12-0fac5098e416)

## 报错原因
由于系统设置的时间格式，在以下代码中用`Newtonsoft.Json`解析这个键值的时候，**返回“2024/12/4/周三 13:47:57”**_（以及类似格式不准确的值）_，**而这样的值无法被后文的`DateTime.Parse`方法识别**，从而引发错误，无法继续部署流程。
```csharp
JObject commitdata = JObject.Parse(CommitInfo);
string LCommitDT = commitdata["committer"]["date"].ToString();
```

## 解决方案
```csharp
JToken dateToken = commitdata["committer"]["date"];
DateTime dateTime = dateToken.ToObject<DateTime>(); // 或者使用 (DateTime)dateToken 如果确定它是 DateTime 类型
string LCommitDT = dateTime.ToString("yyyy/MM/dd HH:mm:ss", CultureInfo.InvariantCulture);
```
经验证，该方法解决了该报错，增强了软件对系统环境的适应能力。

_非常感谢您的反馈，我们将在后续的更新中更注重提升软件对系统环境的适应能力。_
